version: '3.7'

services:
  django:
    volumes:
      - ./static:/static/
    env_file:
      - .env
    build:
      context: src
    depends_on: 
      - db
      
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build: src
    command: celery -A core worker -l info
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - django

volumes:
  static:
  pgdata:
