version: '3.7'

services:

  db:
    ports: 
     - 54321:5432
    container_name: db-x-s
    restart: always
  django:
    container_name: django-x-s
    restart: always
    command: >
      sh -c "python manage.py migrate --no-input &&
          python manage.py connectdb &&
          python manage.py collectstatic --no-input &&
          gunicorn core.wsgi:application --bind 0.0.0.0:8000"
  nginx:
    container_name: nginx-x-s
    restart: always
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django 

  flower:
  container_name: flower
    ports: 
     - 5555:5555
      
volumes:
  static:
  pgdata: